//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("Tacos_Control_Model", "FK_productos", "productos", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TacosControl.Entity.productos), "ventas", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TacosControl.Entity.ventas), true)]
[assembly: EdmRelationshipAttribute("Tacos_Control_Model", "FK_insum", "insumos", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TacosControl.Entity.insumos), "recetas", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TacosControl.Entity.recetas), true)]
[assembly: EdmRelationshipAttribute("Tacos_Control_Model", "FK_prod", "productos", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TacosControl.Entity.productos), "recetas", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TacosControl.Entity.recetas), true)]

#endregion

namespace TacosControl.Entity
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class Tacos_Control_Entities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto Tacos_Control_Entities usando la cadena de conexión encontrada en la sección 'Tacos_Control_Entities' del archivo de configuración de la aplicación.
        /// </summary>
        public Tacos_Control_Entities() : base("name=Tacos_Control_Entities", "Tacos_Control_Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto Tacos_Control_Entities.
        /// </summary>
        public Tacos_Control_Entities(string connectionString) : base(connectionString, "Tacos_Control_Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto Tacos_Control_Entities.
        /// </summary>
        public Tacos_Control_Entities(EntityConnection connection) : base(connection, "Tacos_Control_Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<insumos> insumos
        {
            get
            {
                if ((_insumos == null))
                {
                    _insumos = base.CreateObjectSet<insumos>("insumos");
                }
                return _insumos;
            }
        }
        private ObjectSet<insumos> _insumos;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<productos> productos
        {
            get
            {
                if ((_productos == null))
                {
                    _productos = base.CreateObjectSet<productos>("productos");
                }
                return _productos;
            }
        }
        private ObjectSet<productos> _productos;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<ventas> ventas
        {
            get
            {
                if ((_ventas == null))
                {
                    _ventas = base.CreateObjectSet<ventas>("ventas");
                }
                return _ventas;
            }
        }
        private ObjectSet<ventas> _ventas;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<recetas> recetas
        {
            get
            {
                if ((_recetas == null))
                {
                    _recetas = base.CreateObjectSet<recetas>("recetas");
                }
                return _recetas;
            }
        }
        private ObjectSet<recetas> _recetas;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet insumos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToinsumos(insumos insumos)
        {
            base.AddObject("insumos", insumos);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet productos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToproductos(productos productos)
        {
            base.AddObject("productos", productos);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet ventas. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToventas(ventas ventas)
        {
            base.AddObject("ventas", ventas);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet recetas. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTorecetas(recetas recetas)
        {
            base.AddObject("recetas", recetas);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Tacos_Control_Model", Name="insumos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class insumos : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto insumos.
        /// </summary>
        /// <param name="id_insumo">Valor inicial de la propiedad id_insumo.</param>
        /// <param name="insumo">Valor inicial de la propiedad insumo.</param>
        /// <param name="unidad">Valor inicial de la propiedad unidad.</param>
        public static insumos Createinsumos(global::System.String id_insumo, global::System.String insumo, global::System.String unidad)
        {
            insumos insumos = new insumos();
            insumos.id_insumo = id_insumo;
            insumos.insumo = insumo;
            insumos.unidad = unidad;
            return insumos;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String id_insumo
        {
            get
            {
                return _id_insumo;
            }
            set
            {
                if (_id_insumo != value)
                {
                    Onid_insumoChanging(value);
                    ReportPropertyChanging("id_insumo");
                    _id_insumo = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("id_insumo");
                    Onid_insumoChanged();
                }
            }
        }
        private global::System.String _id_insumo;
        partial void Onid_insumoChanging(global::System.String value);
        partial void Onid_insumoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String insumo
        {
            get
            {
                return _insumo;
            }
            set
            {
                OninsumoChanging(value);
                ReportPropertyChanging("insumo");
                _insumo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("insumo");
                OninsumoChanged();
            }
        }
        private global::System.String _insumo;
        partial void OninsumoChanging(global::System.String value);
        partial void OninsumoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String unidad
        {
            get
            {
                return _unidad;
            }
            set
            {
                OnunidadChanging(value);
                ReportPropertyChanging("unidad");
                _unidad = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("unidad");
                OnunidadChanged();
            }
        }
        private global::System.String _unidad;
        partial void OnunidadChanging(global::System.String value);
        partial void OnunidadChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Tacos_Control_Model", "FK_insum", "recetas")]
        public EntityCollection<recetas> recetas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<recetas>("Tacos_Control_Model.FK_insum", "recetas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<recetas>("Tacos_Control_Model.FK_insum", "recetas", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Tacos_Control_Model", Name="productos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class productos : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto productos.
        /// </summary>
        /// <param name="id_producto">Valor inicial de la propiedad id_producto.</param>
        /// <param name="producto">Valor inicial de la propiedad producto.</param>
        public static productos Createproductos(global::System.String id_producto, global::System.String producto)
        {
            productos productos = new productos();
            productos.id_producto = id_producto;
            productos.producto = producto;
            return productos;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String id_producto
        {
            get
            {
                return _id_producto;
            }
            set
            {
                if (_id_producto != value)
                {
                    Onid_productoChanging(value);
                    ReportPropertyChanging("id_producto");
                    _id_producto = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("id_producto");
                    Onid_productoChanged();
                }
            }
        }
        private global::System.String _id_producto;
        partial void Onid_productoChanging(global::System.String value);
        partial void Onid_productoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String producto
        {
            get
            {
                return _producto;
            }
            set
            {
                OnproductoChanging(value);
                ReportPropertyChanging("producto");
                _producto = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("producto");
                OnproductoChanged();
            }
        }
        private global::System.String _producto;
        partial void OnproductoChanging(global::System.String value);
        partial void OnproductoChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Tacos_Control_Model", "FK_productos", "ventas")]
        public EntityCollection<ventas> ventas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ventas>("Tacos_Control_Model.FK_productos", "ventas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ventas>("Tacos_Control_Model.FK_productos", "ventas", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Tacos_Control_Model", "FK_prod", "recetas")]
        public EntityCollection<recetas> recetas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<recetas>("Tacos_Control_Model.FK_prod", "recetas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<recetas>("Tacos_Control_Model.FK_prod", "recetas", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Tacos_Control_Model", Name="recetas")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class recetas : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto recetas.
        /// </summary>
        /// <param name="id_producto">Valor inicial de la propiedad id_producto.</param>
        /// <param name="id_insumo">Valor inicial de la propiedad id_insumo.</param>
        /// <param name="cantidad">Valor inicial de la propiedad cantidad.</param>
        public static recetas Createrecetas(global::System.String id_producto, global::System.String id_insumo, global::System.Decimal cantidad)
        {
            recetas recetas = new recetas();
            recetas.id_producto = id_producto;
            recetas.id_insumo = id_insumo;
            recetas.cantidad = cantidad;
            return recetas;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String id_producto
        {
            get
            {
                return _id_producto;
            }
            set
            {
                if (_id_producto != value)
                {
                    Onid_productoChanging(value);
                    ReportPropertyChanging("id_producto");
                    _id_producto = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("id_producto");
                    Onid_productoChanged();
                }
            }
        }
        private global::System.String _id_producto;
        partial void Onid_productoChanging(global::System.String value);
        partial void Onid_productoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String id_insumo
        {
            get
            {
                return _id_insumo;
            }
            set
            {
                if (_id_insumo != value)
                {
                    Onid_insumoChanging(value);
                    ReportPropertyChanging("id_insumo");
                    _id_insumo = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("id_insumo");
                    Onid_insumoChanged();
                }
            }
        }
        private global::System.String _id_insumo;
        partial void Onid_insumoChanging(global::System.String value);
        partial void Onid_insumoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal cantidad
        {
            get
            {
                return _cantidad;
            }
            set
            {
                if (_cantidad != value)
                {
                    OncantidadChanging(value);
                    ReportPropertyChanging("cantidad");
                    _cantidad = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("cantidad");
                    OncantidadChanged();
                }
            }
        }
        private global::System.Decimal _cantidad;
        partial void OncantidadChanging(global::System.Decimal value);
        partial void OncantidadChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Tacos_Control_Model", "FK_insum", "insumos")]
        public insumos insumos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<insumos>("Tacos_Control_Model.FK_insum", "insumos").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<insumos>("Tacos_Control_Model.FK_insum", "insumos").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<insumos> insumosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<insumos>("Tacos_Control_Model.FK_insum", "insumos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<insumos>("Tacos_Control_Model.FK_insum", "insumos", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Tacos_Control_Model", "FK_prod", "productos")]
        public productos productos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<productos>("Tacos_Control_Model.FK_prod", "productos").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<productos>("Tacos_Control_Model.FK_prod", "productos").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<productos> productosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<productos>("Tacos_Control_Model.FK_prod", "productos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<productos>("Tacos_Control_Model.FK_prod", "productos", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Tacos_Control_Model", Name="ventas")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ventas : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto ventas.
        /// </summary>
        /// <param name="id_producto">Valor inicial de la propiedad id_producto.</param>
        /// <param name="cantidad">Valor inicial de la propiedad cantidad.</param>
        /// <param name="fecha">Valor inicial de la propiedad fecha.</param>
        public static ventas Createventas(global::System.String id_producto, global::System.Int32 cantidad, global::System.DateTime fecha)
        {
            ventas ventas = new ventas();
            ventas.id_producto = id_producto;
            ventas.cantidad = cantidad;
            ventas.fecha = fecha;
            return ventas;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String id_producto
        {
            get
            {
                return _id_producto;
            }
            set
            {
                if (_id_producto != value)
                {
                    Onid_productoChanging(value);
                    ReportPropertyChanging("id_producto");
                    _id_producto = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("id_producto");
                    Onid_productoChanged();
                }
            }
        }
        private global::System.String _id_producto;
        partial void Onid_productoChanging(global::System.String value);
        partial void Onid_productoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 cantidad
        {
            get
            {
                return _cantidad;
            }
            set
            {
                if (_cantidad != value)
                {
                    OncantidadChanging(value);
                    ReportPropertyChanging("cantidad");
                    _cantidad = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("cantidad");
                    OncantidadChanged();
                }
            }
        }
        private global::System.Int32 _cantidad;
        partial void OncantidadChanging(global::System.Int32 value);
        partial void OncantidadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha
        {
            get
            {
                return _fecha;
            }
            set
            {
                if (_fecha != value)
                {
                    OnfechaChanging(value);
                    ReportPropertyChanging("fecha");
                    _fecha = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("fecha");
                    OnfechaChanged();
                }
            }
        }
        private global::System.DateTime _fecha;
        partial void OnfechaChanging(global::System.DateTime value);
        partial void OnfechaChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Tacos_Control_Model", "FK_productos", "productos")]
        public productos productos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<productos>("Tacos_Control_Model.FK_productos", "productos").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<productos>("Tacos_Control_Model.FK_productos", "productos").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<productos> productosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<productos>("Tacos_Control_Model.FK_productos", "productos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<productos>("Tacos_Control_Model.FK_productos", "productos", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
